#!/bin/bash
#
## =========================================================
## Name: extractResponderHashes
## Auth: litsnarf
## Desc: Extracts hashes from a Responder-Session.log file
## =========================================================
##
## Usage: ./extractResponderHashes [-i|--input] <Responder-Session.log> [-o|--output] [-A]
##    -o, --output <filename>:  [OPTIONAL] Output results into a file. 
##          If not specified, the results are printed in the stdout
##    -i, --input  <filename>:  [OPTIONAL]responder log file to parse
##    -A: [OPTIONAL] Extract all the hashes for every user. If not specified, 
##          it prints only the first occurence in the file (per user)
##

#TODO
# *) Select the time frame to parse
# *) Select the types of hash to extract or All

# Print help
function usage {
  
  if [ "$1" == 1 ] ; then
    echo -e "" && grep -E '^## ?' "$0" | sed -E 's/^## ?//g' | sed -n '7p' && echo -e ""
  else
    grep -E '^## ?' "$0" | sed -E 's/^## ?//g'
  fi
  exit
}

function ifEmpty()
{
    local VAL=$1
    local OPT=$2
    
    if [[ -z "${VAL}" || "${VAL}" =~ ^[[:space:]]*$ || "${VAL}" == -* ]] ; then 
      echo -e "\n  ERROR: Missing argument for option: ${OPT}\n" >&2; 
      exit 1
    fi
}

# print manual if no options
if [ "$1" == "" ] ; then
  usage
fi

INPUT=false
ALLHASH=false


# parse the parameter passes
OPTS=`getopt -o hAi:o: --long input:,output:,help -n 'parse-options' -- "$@"`

if [ $? != 0 ]
then
    usage "1"
    exit 1
fi

eval set -- "$OPTS"

while true; do
  case "$1" in
    -h | --help)      usage ; exit ;;
    -i | --input)     ifEmpty "$2" "$1"; INPUT=$2 ; shift 2 ;;
    -o | --output)    ifEmpty "$2" "$1"; OUTPUT=$2; shift 2 ;;
    -A)               ALLHASH=true ; shift ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

# take the input file name if it is not provided with the -i option but directly in the command
# ex: ./extractResponderHashes pathToFile.log -o out.txt
if [[ -n $1  || $INPUT = "" ]]; then
    INPUT="$1"
else
  echo -e "\n  ERROR: Missing the responder input file! Please check the manual. \n"
  exit
fi

# temporary file to work with
TMP1=$(mktemp tmp.resp.XXXXXXX)
TMP2=$(mktemp tmp.resp.XXXXXXX)
FINALRES=$(mktemp tmp.resp.XXXXXXX)

# remove non UTF-8 characters
cat $INPUT | strings -n 8 >> $TMP1

# extract all hashes for every user and write it: username:DOMAIN::hash
grep -ioE "[^:]+::.+" $TMP1 >> $FINALRES

# extract only one occurence per user (avoid multiple hases for each user)
if [ "$ALLHASH" == false ] ; then
  for user in $(egrep -ioE '(.*::[^.*:]+:)' $FINALRES | sort -u) ; do 
        grep "$user" $FINALRES | grep -ioE "[^:]+::.+$" | tail -n 1 | sort -u >> $TMP2
  done
  cp $TMP2 $FINALRES
fi

# Write the results into a file or stout
if [ "$OUTPUT" == "" ] ; then
  cat $FINALRES #stdout
else
  mv $FINALRES $OUTPUT #file provided in the command
fi

# Delete all temp files
trap "rm -f $TMP1 $FINALRES $TMP2" EXIT
